# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-prov-test

pool:
  vmImage: ubuntu-latest

variables:
  # Top-level variable groups definition
  - group: flask-app-secrets

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'mayaaiuga/azure-prov-test'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'


- task: AzureCLI@2
  inputs:
    azureSubscription: 'aks-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Install kubectl
      az aks install-cli

      # Get AKS credentials
      az aks get-credentials --resource-group 5076a581-terraform-rg --name 5076a581-aks-cluster

      # Verify kubectl context
      kubectl config current-context
      kubectl get nodes
      
      # Create Kubernetes secret
      kubectl create secret generic flask-app-secrets \
        --from-literal=db-server=$(DB_SERVER) \
        --from-literal=db-database=$(DB_DATABASE) \
        --from-literal=db-username=$(DB_USERNAME) \
        --from-literal=db-password=$(DB_PASSWORD) \
        --dry-run=client -o yaml > k8s-secret.yaml
      
      # Apply the Kubernetes secret
      kubectl apply -f k8s-secret.yaml

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'aks-connection'
    azureResourceGroup: '2e3960b5-terraform-rg'
    kubernetesCluster: '2e3960b5-aks-cluster'
    manifests: 'deployment.yaml'