# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-prov-test

pool:
  vmImage: ubuntu-latest

variables:
  - name: DB_SERVER
    value: $(DB_SERVER)
  - name: DB_DATABASE
    value: $(DB_DATABASE)
  - name: DB_USERNAME
    value: $(DB_USERNAME)
  - name: DB_PASSWORD
    value: $(DB_PASSWORD)

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'mayaaiuga/azure-prov-test'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- script: |
    # Create the secrets.yaml file
    cat <<EOF > secrets.yaml
    apiVersion: v1
    kind: Secret
    metadata:
      name: flask-app-secrets
    type: Opaque
    data:
      db-server: $(echo -n $(DB_SERVER) | base64)
      db-database: $(echo -n $(DB_DATABASE) | base64)
      db-username: $(echo -n $(DB_USERNAME) | base64)
      db-password: $(echo -n $(DB_PASSWORD) | base64)
    EOF
  displayName: 'Create Kubernetes Secrets YAML'


- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'aks-connection'
    azureResourceGroup: '9b5daa2d-terraform-rg'
    kubernetesCluster: '9b5daa2d-aks-cluster'
    manifests: |
      secrets.yaml
      deployment.yaml
      