# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-prov-test

pool:
  vmImage: ubuntu-latest

variables:
  - name: DB_SERVER
    value: $(DB_SERVER)
  - name: DB_DATABASE
    value: $(DB_DATABASE)
  - name: DB_USER
    value: $(DB_USER)
  - name: DB_PASSWORD
    value: $(DB_PASSWORD)

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'mayaaiuga/azure-prov-test'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'