#apiVersion: v1
#kind: Secret
#metadata:
###  name: myapp-secrets
#type: Opaque
#data:
#  AZURE_SUBSCRIPTION_ID: NDEzNTU5MTMtYTViNC00MDc3LTk2MmItMDg3ZTg2ZjllNDRl
#  AZURE_CLIENT_ID: ZjliM2FmNDItNTI0YS00NDA2LWI5ZTEtNTZhNjQ3ZGM0NmRm
#  AZURE_CLIENT_SECRET: bzliOFF+Lm5OSkp3RTBJMXhZWjNUVnJsOExIMUtUUno2V3ZGZGNCZw==
#  AZURE_TENANT_ID: ZTg2YjcxZmYtNDBmYy00NzY3LThlOGMtNTM4NGNjNWM5MGVh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: mayaaiuga/flask-app-test:latest 
        ports:
        - containerPort: 5000  # Expose the same port specified in your Dockerfile
        #env:
        #- name: AZURE_SUBSCRIPTION_ID
         # valueFrom:
          #  secretKeyRef:
           #   name: myapp-secrets
            #  key: AZURE_SUBSCRIPTION_ID
        #- name: AZURE_CLIENT_ID
         # valueFrom:
          #  secretKeyRef:
           #   name: myapp-secrets
            #  key: AZURE_CLIENT_ID
        #- name: AZURE_CLIENT_SECRET
         # valueFrom:
          #  secretKeyRef:
           #   name: myapp-secrets
            #  key: AZURE_CLIENT_SECRET
        #- name: AZURE_TENANT_ID
         # valueFrom:
          #  secretKeyRef:
           #   name: myapp-secrets
            #  key: AZURE_TENANT_ID
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-services
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80  # Port for internal communication within the cluster
    targetPort: 5000  # Port exposed by your container
  type: ClusterIP  # Internal service

     
