---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: flask-app
  template:
    metadata:
      labels: 
        app: flask-app
    spec:
      containers:
      - name: flask-web-app
        image: ben034/flask-app:latest
        ports:
          - containerPort: 5000
        env:
        - name: DB_SERVER
          valueFrom:
            secretKeyRef:
              name: secret-name
              key: db-server
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: secret-name
              key: db-database 
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-name
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-name
              key: db-password 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
  