apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secrets
type: Opaque
data:
  db-server: ZGV2b3BzLXByb2plY3Qtc2VydmVyLmRhdGFiYXNlLndpbmRvd3MubmV0 # base64_encoded 'devops-project-server.database.windows.net'
  db-database: b3JkZXJzLWRi # base64_encoded 'orders-db'
  db-username: bWF5YQ== # base64_encoded 'maya'
  db-password: QWlDb3JlMTIzNw== # base64_encoded 'AiCore1237'
