apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secrets
type: Opaque
data:
  db-server: $(echo -n $(DB_SERVER) | base64)
  db-database: $(echo -n $(DB_DATABASE) | base64)
  db-username: $(echo -n $(DB_USERNAME) | base64)
  db-password: $(echo -n $(DB_PASSWORD) | base64)
