apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secrets
type: Opaque
data:
  db-server: ZGV2b3BzLXByb2plY3Qtc2VydmVyLmRhdGFiYXNlLndpbmRvd3MubmV0 
  db-database: b3JkZXJzLWRi 
  db-username: bWF5YQ== 
  db-password: QWlDb3JlMTIzNw== 
